In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../data/BBDD.csv', sep=',')

df.head()

,Imported Profiles,Enrich LI Profile,Company Name,First Name,Last Name,Full Name,Job Title,Location,Company Domain,LinkedIn Profile,...,Title - Experience,Title - Certifications,Company Name - Certifications,Summary - Volunteering,Role - Volunteering,Company Name - Volunteering,Title - Publications,Title - Latest Experience,Company - Latest Experience,Is Current - Latest Experience
0,1,Gonzalo Suárez,Mahou San Miguel,Gonzalo,Suárez,Gonzalo Suárez,Técnico en Ingeniería de Activos Industriales,"Figueres, Catalonia, Spain",mahou-sanmiguel.com,https://www.linkedin.com/in/gonzalosys/,...,Sr RME Technician,Basic Life Support (BLS),ERC European Resuscitation Council,NaN,NaN,NaN,NaN,Sr RME Technician,Amazon,True
1,2,Javier Landivar Castedo,LRH Consultores,Javier,Landivar Castedo,Javier Landivar Castedo,Consultor Senior,"Santa Cruz de la Sierra, Santa Cruz, Bolivia",lrhconsultores.com,https://www.linkedin.com/in/javierlandivarcast...,...,Consultor Senior,Diplomado en Análisis Económico y Desarrollo H...,Edutin Academy,NaN,NaN,NaN,NaN,Consultor Senior,LRH Consultores,True
2,3,Daniel Miranda Ortiz,Colgram S.A.,Daniel,Ortiz,Daniel Alejandro Miranda Ortiz,Subgerente de Control de Gestin Corporativo,"Santiago, Santiago Metropolitan Region, Chile",opaline.cl,https://www.linkedin.com/in/danielmirandaortiz/,...,SubGerente de Planificación y Control de Gestión,Indicadores clave y tableros de mando para la ...,Universidad de Chile,Participe como voluntario en la Cruz Roja de V...,Voluntario,NaN,NaN,Subgerente de Control de Gestin Corporativo,Colgram S.A.,True
3,4,Rossana Mercado,Velozient,Rossana,Mercado,Rossana Mercado,Senior Technical Recruiting Specialist,"La Paz, Bolivia",velozient.com,https://www.linkedin.com/in/rossana-mercado/,...,Senior Technical Recruiting Specialist,Digital Transformation Tips,LinkedIn,NaN,NaN,NaN,NaN,Senior Technical Recruiting Specialist,Velozient,True
4,5,Enrique Maldonado,NaN,Enrique,Maldonado,Enrique Maldonado,Propietario,"La Paz, Bolivia",NaN,https://www.linkedin.com/in/emaldonado2/,...,Gerente - Propietario,QPLS1x: Six Sigma: Define and Measure,Technical University of Munich,NaN,NaN,NaN,NaN,Gerente - Propietario,Khofisuyo,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4311 entries, 0 to 4310
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Imported Profiles               4311 non-null   int64
 1   Enrich LI Profile               3176 non-null   object
 2   Company Name                    3112 non-null   object
 3   First Name                      4311 non-null   object
 4   Last Name                       4310 non-null   object
 5   Full Name                       4311 non-null   object
 6   Job Title                       4222 non-null   object
 7   Location                        4308 non-null   object
 8   Company Domain                  2980 non-null   object
 9   LinkedIn Profile                4311 non-null   object
 10  Enrich Person                   2880 non-null   object
 11  Title                           2813 non-null   object
 12  Connections                     2833 non-null   float64
 13  Num Followers                   2831 non-null   float64
 14  Headline                        2830 non-null   object
 15  Summary                         1940 non-null   object
 16  Url - Experience                2316 non-null   object
 17  Company - Experience            2819 non-null   object
 18  Summary - Experience            944 non-null    object
 19  Locality - Experience           2210 non-null   object
 20  Is Current - Experience         4311 non-null   bool
 21  Grade - Education               89 non-null     float64
 22  Degree - Education              2770 non-null   object
 23  School Name - Education         2830 non-null   object
 24  Field Of Study - Education      2292 non-null   object
 25  Country                         2831 non-null   object
 26  Location Name                   2829 non-null   object
 27  Summary - Awards                238 non-null    object
 28  Course Number - Courses         477 non-null    object
 29  Title - Courses                 477 non-null    object
 30  Title - Projects                158 non-null    object
 31  Summary - Projects              113 non-null    object
 32  Language - Languages            1524 non-null   object
 33  Proficiency - Languages         1216 non-null   object
 34  Title - Experience              2821 non-null   object
 35  Title - Certifications          1209 non-null   object
 36  Company Name - Certifications   1198 non-null   object
 37  Summary - Volunteering          297 non-null    object
 38  Role - Volunteering             560 non-null    object
 39  Company Name - Volunteering     0 non-null      float64
 40  Title - Publications            0 non-null      float64
 41  Title - Latest Experience       2545 non-null   object
 42  Company - Latest Experience     2532 non-null   object
 43  Is Current - Latest Experience  4311 non-null   bool
dtypes: bool(2), float64(5), int64(1), object(36)
memory usage: 1.4+ MB

In [5]:
df_interim = df.copy()

In [6]:
# Filtramos solo los Headlines con valores validos
df_interim = df_interim[df['Headline'].notna()]
df_interim.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830 entries, 0 to 2899
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Imported Profiles               2830 non-null   int64
 1   Enrich LI Profile               2829 non-null   object
 2   Company Name                    2066 non-null   object
 3   First Name                      2830 non-null   object
 4   Last Name                       2830 non-null   object
 5   Full Name                       2830 non-null   object
 6   Job Title                       2764 non-null   object
 7   Location                        2828 non-null   object
 8   Company Domain                  1976 non-null   object
 9   LinkedIn Profile                2830 non-null   object
 10  Enrich Person                   2830 non-null   object
 11  Title                           2810 non-null   object
 12  Connections                     2830 non-null   float64
 13  Num Followers                   2830 non-null   float64
 14  Headline                        2830 non-null   object
 15  Summary                         1940 non-null   object
 16  Url - Experience                2313 non-null   object
 17  Company - Experience            2816 non-null   object
 18  Summary - Experience            944 non-null    object
 19  Locality - Experience           2207 non-null   object
 20  Is Current - Experience         2830 non-null   bool
 21  Grade - Education               89 non-null     float64
 22  Degree - Education              2767 non-null   object
 23  School Name - Education         2827 non-null   object
 24  Field Of Study - Education      2290 non-null   object
 25  Country                         2828 non-null   object
 26  Location Name                   2826 non-null   object
 27  Summary - Awards                238 non-null    object
 28  Course Number - Courses         476 non-null    object
 29  Title - Courses                 476 non-null    object
 30  Title - Projects                158 non-null    object
 31  Summary - Projects              113 non-null    object
 32  Language - Languages            1523 non-null   object
 33  Proficiency - Languages         1215 non-null   object
 34  Title - Experience              2818 non-null   object
 35  Title - Certifications          1209 non-null   object
 36  Company Name - Certifications   1198 non-null   object
 37  Summary - Volunteering          297 non-null    object
 38  Role - Volunteering             559 non-null    object
 39  Company Name - Volunteering     0 non-null      float64
 40  Title - Publications            0 non-null      float64
 41  Title - Latest Experience       2542 non-null   object
 42  Company - Latest Experience     2529 non-null   object
 43  Is Current - Latest Experience  2830 non-null   bool
dtypes: bool(2), float64(5), int64(1), object(36)
memory usage: 956.2+ KB

In [7]:
df_interim = df_interim.drop(columns=[
    'Imported Profiles',
    'Title - Publications', 
    'Company Name - Volunteering', 
    'Enrich LI Profile', 'First Name', 
    'Last Name', 'Enrich Person', 
    'Company Domain', 
    'Course Number - Courses', 
    'Company Name - Certifications',
    ])
df_interim.head()

,Company Name,Full Name,Job Title,Location,LinkedIn Profile,Title,Connections,Num Followers,Headline,Summary,...,Summary - Projects,Language - Languages,Proficiency - Languages,Title - Experience,Title - Certifications,Summary - Volunteering,Role - Volunteering,Title - Latest Experience,Company - Latest Experience,Is Current - Latest Experience
0,Mahou San Miguel,Gonzalo Suárez,Técnico en Ingeniería de Activos Industriales,"Figueres, Catalonia, Spain",https://www.linkedin.com/in/gonzalosys/,Sr RME Technician,24157.0,30451.0,Mechatronics Engineer,Soy Ingeniero en Mecatrónica especializado en ...,...,NaN,Español,Native or bilingual proficiency,Sr RME Technician,Basic Life Support (BLS),NaN,NaN,Sr RME Technician,Amazon,True
1,LRH Consultores,Javier Landivar Castedo,Consultor Senior,"Santa Cruz de la Sierra, Santa Cruz, Bolivia",https://www.linkedin.com/in/javierlandivarcast...,Consultor Senior,29896.0,30168.0,Gestión del Talento | Estrategias Personalizad...,¿Alguna vez te has preguntado por qué algunas ...,...,NaN,Español,Native or bilingual proficiency,Consultor Senior,Diplomado en Análisis Económico y Desarrollo H...,NaN,NaN,Consultor Senior,LRH Consultores,True
2,Colgram S.A.,Daniel Alejandro Miranda Ortiz,Subgerente de Control de Gestin Corporativo,"Santiago, Santiago Metropolitan Region, Chile",https://www.linkedin.com/in/danielmirandaortiz/,Subgerente de Control de Gestin Corporativo,29806.0,29864.0,Ingeniero Comercial | Magister en Planificació...,Amplio dominio en el área de administración fi...,...,NaN,Español,Native or bilingual proficiency,SubGerente de Planificación y Control de Gestión,Indicadores clave y tableros de mando para la ...,Participe como voluntario en la Cruz Roja de V...,Voluntario,Subgerente de Control de Gestin Corporativo,Colgram S.A.,True
3,Velozient,Rossana Mercado,Senior Technical Recruiting Specialist,"La Paz, Bolivia",https://www.linkedin.com/in/rossana-mercado/,Senior Technical Recruiting Specialist,28010.0,29385.0,Senior Technical Recruiter SpecialistIT Head H...,Hi! You can call me Ross (:\n\nI’m a psycholo...,...,NaN,Español,Native or bilingual proficiency,Senior Technical Recruiting Specialist,Digital Transformation Tips,NaN,NaN,Senior Technical Recruiting Specialist,Velozient,True
4,NaN,Enrique Maldonado,Propietario,"La Paz, Bolivia",https://www.linkedin.com/in/emaldonado2/,Gerente - Propietario,28546.0,28490.0,Specialty Coffee | Hospitality | Consultant,NaN,...,Operational and administrative diagnostic of t...,English,Professional working proficiency,Gerente - Propietario,QPLS1x: Six Sigma: Define and Measure,NaN,NaN,Gerente - Propietario,Khofisuyo,True

In [8]:
df_interim.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830 entries, 0 to 2899
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Company Name                    2066 non-null   object
 1   Full Name                       2830 non-null   object
 2   Job Title                       2764 non-null   object
 3   Location                        2828 non-null   object
 4   LinkedIn Profile                2830 non-null   object
 5   Title                           2810 non-null   object
 6   Connections                     2830 non-null   float64
 7   Num Followers                   2830 non-null   float64
 8   Headline                        2830 non-null   object
 9   Summary                         1940 non-null   object
 10  Url - Experience                2313 non-null   object
 11  Company - Experience            2816 non-null   object
 12  Summary - Experience            944 non-null    object
 13  Locality - Experience           2207 non-null   object
 14  Is Current - Experience         2830 non-null   bool
 15  Grade - Education               89 non-null     float64
 16  Degree - Education              2767 non-null   object
 17  School Name - Education         2827 non-null   object
 18  Field Of Study - Education      2290 non-null   object
 19  Country                         2828 non-null   object
 20  Location Name                   2826 non-null   object
 21  Summary - Awards                238 non-null    object
 22  Title - Courses                 476 non-null    object
 23  Title - Projects                158 non-null    object
 24  Summary - Projects              113 non-null    object
 25  Language - Languages            1523 non-null   object
 26  Proficiency - Languages         1215 non-null   object
 27  Title - Experience              2818 non-null   object
 28  Title - Certifications          1209 non-null   object
 29  Summary - Volunteering          297 non-null    object
 30  Role - Volunteering             559 non-null    object
 31  Title - Latest Experience       2542 non-null   object
 32  Company - Latest Experience     2529 non-null   object
 33  Is Current - Latest Experience  2830 non-null   bool
dtypes: bool(2), float64(3), object(29)
memory usage: 735.1+ KB

In [9]:
df_int_1 = df_interim.copy()

In [10]:
df_int_1['Location'].sample(10)

825                              Santa Cruz, Bolivia
681                              Cochabamba, Bolivia
410                                          Bolivia
1985                                         Bolivia
444                                          Bolivia
687     Santa Cruz de la Sierra, Santa Cruz, Bolivia
664     Santa Cruz de la Sierra, Santa Cruz, Bolivia
2446                                         Bolivia
2565                                         Sverige
287     Santa Cruz de la Sierra, Santa Cruz, Bolivia
Name: Location, dtype: object

In [11]:
# Función para extraer el país y la ciudad
def extract_location(location):
    if isinstance(location, str):  # Verifica si es una cadena
        parts = location.split(',')
        country = parts[-1].strip()  # Última parte es el país
        city = ','.join(part.strip() for part in parts[:-1]).strip()  # Resto es la ciudad
        return pd.Series([country, city])
    else:
        return pd.Series([None, None])  # Devuelve None si no es una cadena

# Aplicar la función y crear nuevas columnas
df_int_1[['Country', 'City']] = df_int_1['Location'].apply(extract_location)

# Mostrar el DataFrame resultante
print(df_int_1)

                                           Company Name  \
0                                      Mahou San Miguel
1                                       LRH Consultores
2                                          Colgram S.A.
3                                             Velozient
4                                                   NaN
...                                                 ...
2895                              Blue Lotus Consultora
2896  Actualisap Consultores Bolivia S.A. | SAP GOLD...
2897                                                NaN
2898                                         Embol S.A.
2899                                             Dopper

                           Full Name  \
0                     Gonzalo Suárez
1            Javier Landivar Castedo
2     Daniel Alejandro Miranda Ortiz
3                    Rossana Mercado
4                  Enrique Maldonado
...                              ...
2895                   Sdenka Patiño
2896                  Adiva Sanjines
2897          William Espinoza Quinn
2898             Sergio Pérez Meleán
2899    Marjolein ten Berge - Gräper

                                              Job Title  \
0         Técnico en Ingeniería de Activos Industriales
1                                      Consultor Senior
2           Subgerente de Control de Gestin Corporativo
3                Senior Technical Recruiting Specialist
4                                           Propietario
...                                                 ...
2895                             Consultora de empresas
2896                             Encargada de Marketing
2897                                    Auditor interno
2898                        Gestor de Desarrollo Humano
2899  International sales and new busines developmen...

                                           Location  \
0                        Figueres, Catalonia, Spain
1      Santa Cruz de la Sierra, Santa Cruz, Bolivia
2     Santiago, Santiago Metropolitan Region, Chile
3                                   La Paz, Bolivia
4                                   La Paz, Bolivia
...                                             ...
2895   Santa Cruz de la Sierra, Santa Cruz, Bolivia
2896                                La Paz, Bolivia
2897                                La Paz, Bolivia
2898                            Cochabamba, Bolivia
2899                      The Randstad, Netherlands

                                       LinkedIn Profile  \
0               https://www.linkedin.com/in/gonzalosys/
1     https://www.linkedin.com/in/javierlandivarcast...
2       https://www.linkedin.com/in/danielmirandaortiz/
3          https://www.linkedin.com/in/rossana-mercado/
4              https://www.linkedin.com/in/emaldonado2/
...                                                 ...
2895          https://www.linkedin.com/in/sdenkapatino/
2896        https://www.linkedin.com/in/adiva-sanjines/
2897  https://www.linkedin.com/in/william-espinoza-q...
2898  https://www.linkedin.com/in/sergio-pérez-meleá...
2899     https://www.linkedin.com/in/marjoleintenberge/

                                                  Title  Connections  \
0                                     Sr RME Technician      24157.0
1                                      Consultor Senior      29896.0
2           Subgerente de Control de Gestin Corporativo      29806.0
3                Senior Technical Recruiting Specialist      28010.0
4                                 Gerente - Propietario      28546.0
...                                                 ...          ...
2895                             Consultora de empresas        964.0
2896                             Encargada de Marketing        965.0
2897                                    Auditor interno        827.0
2898                        Gestor de Desarrollo Humano       1024.0
2899  International sales and new busines developmen...        983.0

      Num Followers                                           Headline  \
0           30451.0                              Mechatronics Engineer
1           30168.0  Gestión del Talento | Estrategias Personalizad...
2           29864.0  Ingeniero Comercial | Magister en Planificació...
3           29385.0  Senior Technical Recruiter SpecialistIT Head H...
4           28490.0        Specialty Coffee | Hospitality | Consultant
...             ...                                                ...
2895          995.0  Consultora de empresas | Especialista en polít...
2896         1013.0  Supporting companies on their way to becoming ...
2897          983.0  Auditor Interno | Auditor Externo | PwC | Erns...
2898         1026.0  Business Strategy Consultant | Ing. Comercial ...
2899          974.0  Freelance ǀ Interim ǀ Purpose driven (retail) ...

                                                Summary  ...  \
0     Soy Ingeniero en Mecatrónica especializado en ...  ...
1     ¿Alguna vez te has preguntado por qué algunas ...  ...
2     Amplio dominio en el área de administración fi...  ...
3      Hi! You can call me Ross (:\n\nI’m a psycholo...  ...
4                                                   NaN  ...
...                                                 ...  ...
2895  Soy una consultora de empresas con más de diez...  ...
2896  Especialista en Marketing, apoyando en el desa...  ...
2897  Con una trayectoria de más de 25 años, he dedi...  ...
2898  Crafting strategic narratives that drive busin...  ...
2899  I am an energetic, creative, positive minded, ...  ...

     Language - Languages           Proficiency - Languages  \
0                 Español   Native or bilingual proficiency
1                 Español   Native or bilingual proficiency
2                 Español   Native or bilingual proficiency
3                 Español   Native or bilingual proficiency
4                 English  Professional working proficiency
...                   ...                               ...
2895                  NaN                               NaN
2896              English  Professional working proficiency
2897                  NaN                               NaN
2898              Español   Native or bilingual proficiency
2899                Dutch   Native or bilingual proficiency

                                     Title - Experience  \
0                                     Sr RME Technician
1                                      Consultor Senior
2     SubGerente de Planificación y Control de Gestión
3                Senior Technical Recruiting Specialist
4                                 Gerente - Propietario
...                                                 ...
2895                             Consultora de empresas
2896                             Encargada de Marketing
2897                                    Auditor interno
2898                        Gestor de Desarrollo Humano
2899  International sales and new busines developmen...

                                 Title - Certifications  \
0                              Basic Life Support (BLS)
1     Diplomado en Análisis Económico y Desarrollo H...
2     Indicadores clave y tableros de mando para la ...
3                           Digital Transformation Tips
4                 QPLS1x: Six Sigma: Define and Measure
...                                                 ...
2895       ESTIMACIÓN DE APETITO POR RIESGO OPERACIONAL
2896  Business Knowledge 2023 - Partner Marketing Ex...
2897                                                NaN
2898                                     TOEFL iBT (C1)
2899                                                NaN

                                 Summary - Volunteering  Role - Volunteering  \
0                                                   NaN                  NaN
1                                                   NaN                  NaN
2     Participe como voluntario en la Cruz Roja de V...           Voluntario
3                                                   NaN                  NaN
4                                                   NaN                  NaN
...                                                 ...                  ...
2895                                                NaN                  NaN
2896  Rotaract es un programa de Rotary Internationa...             Tesorera
2897                                                NaN                  NaN
2898                                                NaN                  NaN
2899  Through a monitoring system Giving Back aims t...               Mentor

                              Title - Latest Experience  \
0                                     Sr RME Technician
1                                      Consultor Senior
2           Subgerente de Control de Gestin Corporativo
3                Senior Technical Recruiting Specialist
4                                 Gerente - Propietario
...                                                 ...
2895                             Consultora de empresas
2896                             Encargada de Marketing
2897                                    Auditor interno
2898                                                NaN
2899  International sales and new busines developmen...

                Company - Latest Experience Is Current - Latest Experience  \
0                                    Amazon                           True
1                           LRH Consultores                           True
2                              Colgram S.A.                           True
3                                 Velozient                           True
4                                 Khofisuyo                           True
...                                     ...                            ...
2895                  Blue Lotus Consultora                           True
2896                                Celeren                           True
2897  EQ Auditoría, Asesoría y Capacitación                           True
2898                                    NaN                          False
2899                                 Dopper                           True

                                       City
0                        Figueres,Catalonia
1        Santa Cruz de la Sierra,Santa Cruz
2     Santiago,Santiago Metropolitan Region
3                                    La Paz
4                                    La Paz
...                                     ...
2895     Santa Cruz de la Sierra,Santa Cruz
2896                                 La Paz
2897                                 La Paz
2898                             Cochabamba
2899                           The Randstad

[2830 rows x 35 columns]

In [12]:
df_int_1['Country'].sample(20, random_state=1210)

2521                             Germany
2092                             Bolivia
768                              Bolivia
1154                             Bolivia
247                              Bolivia
1422                             Bolivia
2477                             Bolivia
2793                             Bolivia
816                              Bolivia
2576    Greater Madrid Metropolitan Area
2423                             Bolivia
2347                             Bolivia
1883                             Bolivia
391                              Bolivia
1190                             Bolivia
1386                             Bolivia
608                              Bolivia
1720                             Bolivia
93                               Bolivia
1121                             Bolivia
Name: Country, dtype: object

In [13]:
country_mapping = {
    "Los Angeles Metropolitan Area": "United States",
    "Greater Minneapolis-St. Paul Area": "United States",
    "Mexico City Metropolitan Area": "Mexico",
    "Valparaiso Metropolitan Area": "Chile",
    "Greater São Paulo Area": "Brazil",
    "Greater Madrid Metropolitan Area": "Spain",
    "New York City Metropolitan Area": "United States",
    "Lausanne Metropolitan Area": "Switzerland",
    "Greater Rome Metropolitan Area": "Italy",
    "Porto Metropolitan Area": "Portugal",
    "Metro Jacksonville": "United States",
    "Greater Stockholm Metropolitan Area": "Sverige",
    "Miami-Fort Lauderdale Area": "United States",
    "Midland-Odessa Area": "United States",
    "Greater Seattle Area": "United States",
    "Brasil": "Brazil",
    "Perú": "Peru",
    "Spain": "Spain",
    "Amsterdam Area": "Netherlands",
    "Argentina Metropolitan Area": "Argentina",
    "Berlin Metropolitan Area": "Germany",
    "Bogotá D.C. Metropolitan Area": "Colombia",
    "Brussels Metropolitan Area": "Belgium",
    "Cologne Bonn Region": "Germany",
    "Dallas-Fort Worth Metroplex": "United States",
    "Denver Metropolitan Area": "United States",
    "Frankfurt Rhine-Main Metropolitan Area": "Germany",
    "Greater Barcelona Metropolitan Area": "Spain",
    "Greater Buenos Aires": "Argentina",
    "Greater Gothenburg Metropolitan Area": "Sverige",
    "Greater Hamburg Area": "Germany",
    "Greater Houston": "United States",
    "Greater Munich Metropolitan Area": "Germany",
    "Greater Paris Metropolitan Region": "France",
    "Greater Phoenix Area": "United States",
    "Greater Sevilla Metropolitan Area": "Spain",
    "Greater Strasbourg Metropolitan Area": "France",
    "Greater Tucson Area": "United States",
    "Greater Valencia Metropolitan Area": "Spain",
    "Greater Vancouver Metropolitan Area": "Canada",
    "Guayaquil Metropolitan Area": "Ecuador",
    "Hannover-Braunschweig-Göttingen-Wolfsburg Region": "Germany",
    "Lima Metropolitan Area": "Peru",
    "Lugano Metropolitan Area": "Switzerland",
    "New Zealand": "New Zealand",
    "Raleigh-Durham-Chapel Hill Area": "United States",
    "San Francisco Bay Area": "United States",
    "San José Metropolitan Area": "Costa Rica",
    "Stuttgart Region": "Germany",
    "الاحمدي الكويت": "Kuwait",
    "الدوحة قطر": "Qatar",
    "الشرقية الدمام السعودية": "Saudi Arabia",
    "دبي دبي الإمارات العربية المتحدة": "United Arab Emirates",
    "Washington DC-Baltimore Area": "United States"
}
# Reemplazar los valores atípicos en la columna 'Country'
df_int_1['Country'] = df_int_1['Country'].replace(country_mapping)

# Mostrar el DataFrame resultante
print(df_int_1)

                                           Company Name  \
0                                      Mahou San Miguel
1                                       LRH Consultores
2                                          Colgram S.A.
3                                             Velozient
4                                                   NaN
...                                                 ...
2895                              Blue Lotus Consultora
2896  Actualisap Consultores Bolivia S.A. | SAP GOLD...
2897                                                NaN
2898                                         Embol S.A.
2899                                             Dopper

                           Full Name  \
0                     Gonzalo Suárez
1            Javier Landivar Castedo
2     Daniel Alejandro Miranda Ortiz
3                    Rossana Mercado
4                  Enrique Maldonado
...                              ...
2895                   Sdenka Patiño
2896                  Adiva Sanjines
2897          William Espinoza Quinn
2898             Sergio Pérez Meleán
2899    Marjolein ten Berge - Gräper

                                              Job Title  \
0         Técnico en Ingeniería de Activos Industriales
1                                      Consultor Senior
2           Subgerente de Control de Gestin Corporativo
3                Senior Technical Recruiting Specialist
4                                           Propietario
...                                                 ...
2895                             Consultora de empresas
2896                             Encargada de Marketing
2897                                    Auditor interno
2898                        Gestor de Desarrollo Humano
2899  International sales and new busines developmen...

                                           Location  \
0                        Figueres, Catalonia, Spain
1      Santa Cruz de la Sierra, Santa Cruz, Bolivia
2     Santiago, Santiago Metropolitan Region, Chile
3                                   La Paz, Bolivia
4                                   La Paz, Bolivia
...                                             ...
2895   Santa Cruz de la Sierra, Santa Cruz, Bolivia
2896                                La Paz, Bolivia
2897                                La Paz, Bolivia
2898                            Cochabamba, Bolivia
2899                      The Randstad, Netherlands

                                       LinkedIn Profile  \
0               https://www.linkedin.com/in/gonzalosys/
1     https://www.linkedin.com/in/javierlandivarcast...
2       https://www.linkedin.com/in/danielmirandaortiz/
3          https://www.linkedin.com/in/rossana-mercado/
4              https://www.linkedin.com/in/emaldonado2/
...                                                 ...
2895          https://www.linkedin.com/in/sdenkapatino/
2896        https://www.linkedin.com/in/adiva-sanjines/
2897  https://www.linkedin.com/in/william-espinoza-q...
2898  https://www.linkedin.com/in/sergio-pérez-meleá...
2899     https://www.linkedin.com/in/marjoleintenberge/

                                                  Title  Connections  \
0                                     Sr RME Technician      24157.0
1                                      Consultor Senior      29896.0
2           Subgerente de Control de Gestin Corporativo      29806.0
3                Senior Technical Recruiting Specialist      28010.0
4                                 Gerente - Propietario      28546.0
...                                                 ...          ...
2895                             Consultora de empresas        964.0
2896                             Encargada de Marketing        965.0
2897                                    Auditor interno        827.0
2898                        Gestor de Desarrollo Humano       1024.0
2899  International sales and new busines developmen...        983.0

      Num Followers                                           Headline  \
0           30451.0                              Mechatronics Engineer
1           30168.0  Gestión del Talento | Estrategias Personalizad...
2           29864.0  Ingeniero Comercial | Magister en Planificació...
3           29385.0  Senior Technical Recruiter SpecialistIT Head H...
4           28490.0        Specialty Coffee | Hospitality | Consultant
...             ...                                                ...
2895          995.0  Consultora de empresas | Especialista en polít...
2896         1013.0  Supporting companies on their way to becoming ...
2897          983.0  Auditor Interno | Auditor Externo | PwC | Erns...
2898         1026.0  Business Strategy Consultant | Ing. Comercial ...
2899          974.0  Freelance ǀ Interim ǀ Purpose driven (retail) ...

                                                Summary  ...  \
0     Soy Ingeniero en Mecatrónica especializado en ...  ...
1     ¿Alguna vez te has preguntado por qué algunas ...  ...
2     Amplio dominio en el área de administración fi...  ...
3      Hi! You can call me Ross (:\n\nI’m a psycholo...  ...
4                                                   NaN  ...
...                                                 ...  ...
2895  Soy una consultora de empresas con más de diez...  ...
2896  Especialista en Marketing, apoyando en el desa...  ...
2897  Con una trayectoria de más de 25 años, he dedi...  ...
2898  Crafting strategic narratives that drive busin...  ...
2899  I am an energetic, creative, positive minded, ...  ...

     Language - Languages           Proficiency - Languages  \
0                 Español   Native or bilingual proficiency
1                 Español   Native or bilingual proficiency
2                 Español   Native or bilingual proficiency
3                 Español   Native or bilingual proficiency
4                 English  Professional working proficiency
...                   ...                               ...
2895                  NaN                               NaN
2896              English  Professional working proficiency
2897                  NaN                               NaN
2898              Español   Native or bilingual proficiency
2899                Dutch   Native or bilingual proficiency

                                     Title - Experience  \
0                                     Sr RME Technician
1                                      Consultor Senior
2     SubGerente de Planificación y Control de Gestión
3                Senior Technical Recruiting Specialist
4                                 Gerente - Propietario
...                                                 ...
2895                             Consultora de empresas
2896                             Encargada de Marketing
2897                                    Auditor interno
2898                        Gestor de Desarrollo Humano
2899  International sales and new busines developmen...

                                 Title - Certifications  \
0                              Basic Life Support (BLS)
1     Diplomado en Análisis Económico y Desarrollo H...
2     Indicadores clave y tableros de mando para la ...
3                           Digital Transformation Tips
4                 QPLS1x: Six Sigma: Define and Measure
...                                                 ...
2895       ESTIMACIÓN DE APETITO POR RIESGO OPERACIONAL
2896  Business Knowledge 2023 - Partner Marketing Ex...
2897                                                NaN
2898                                     TOEFL iBT (C1)
2899                                                NaN

                                 Summary - Volunteering  Role - Volunteering  \
0                                                   NaN                  NaN
1                                                   NaN                  NaN
2     Participe como voluntario en la Cruz Roja de V...           Voluntario
3                                                   NaN                  NaN
4                                                   NaN                  NaN
...                                                 ...                  ...
2895                                                NaN                  NaN
2896  Rotaract es un programa de Rotary Internationa...             Tesorera
2897                                                NaN                  NaN
2898                                                NaN                  NaN
2899  Through a monitoring system Giving Back aims t...               Mentor

                              Title - Latest Experience  \
0                                     Sr RME Technician
1                                      Consultor Senior
2           Subgerente de Control de Gestin Corporativo
3                Senior Technical Recruiting Specialist
4                                 Gerente - Propietario
...                                                 ...
2895                             Consultora de empresas
2896                             Encargada de Marketing
2897                                    Auditor interno
2898                                                NaN
2899  International sales and new busines developmen...

                Company - Latest Experience Is Current - Latest Experience  \
0                                    Amazon                           True
1                           LRH Consultores                           True
2                              Colgram S.A.                           True
3                                 Velozient                           True
4                                 Khofisuyo                           True
...                                     ...                            ...
2895                  Blue Lotus Consultora                           True
2896                                Celeren                           True
2897  EQ Auditoría, Asesoría y Capacitación                           True
2898                                    NaN                          False
2899                                 Dopper                           True

                                       City
0                        Figueres,Catalonia
1        Santa Cruz de la Sierra,Santa Cruz
2     Santiago,Santiago Metropolitan Region
3                                    La Paz
4                                    La Paz
...                                     ...
2895     Santa Cruz de la Sierra,Santa Cruz
2896                                 La Paz
2897                                 La Paz
2898                             Cochabamba
2899                           The Randstad

[2830 rows x 35 columns]

In [14]:
df_int_1['Country'].unique()

array(['Spain', 'Bolivia', 'Chile', 'Ecuador', 'United States',
       'Costa Rica', 'Israel', 'Netherlands', 'Germany', 'Ireland',
       'Argentina', 'Canada', 'France', 'Belgium', 'Mexico', 'Paraguay',
       'Poland', 'Panama', 'Peru', 'Switzerland', 'Norway', 'Guatemala',
       'Brazil', 'Sweden', 'Australia', 'Uruguay', 'United Kingdom',
       'Colombia', 'Denmark', 'Italy', 'Portugal', 'Nicaragua', 'España',
       'Sverige', 'Malta', 'Puerto Rico', 'Russia', 'Honduras', 'Austria',
       'Philippines', 'Singapore', 'Venezuela', None, 'Qatar',
       'Luxembourg', 'Panamá', 'Vietnam', 'China', 'Kuwait', 'Finland',
       'Croatia', 'Saudi Arabia', 'Dominican Republic', 'Cayman Islands',
       'Cyprus', 'Deutschland', 'French Guiana', 'United Arab Emirates',
       'El Salvador', 'Mongolia', 'Latin America'], dtype=object)

In [15]:
# 0 Si esta en Bolivia y 1 si esta en el exterior
df_int_1['International'] = df_int_1['Country'].apply(lambda x: 0 if x == 'Bolivia' else 1)
df_int_1.sample(10)

,Company Name,Full Name,Job Title,Location,LinkedIn Profile,Title,Connections,Num Followers,Headline,Summary,...,Proficiency - Languages,Title - Experience,Title - Certifications,Summary - Volunteering,Role - Volunteering,Title - Latest Experience,Company - Latest Experience,Is Current - Latest Experience,City,International
1857,ProcessMaker,Armando Vargas,Senior Customer Success Manager,"La Paz, Bolivia",https://www.linkedin.com/in/armando-vargas-362...,Senior Customer Success Manager,1810.0,1838.0,SaaS Customer Success Manager | Business Devel...,Multi-skilled professional with an MBA degree ...,...,Professional working proficiency,Senior Customer Success Manager,Admin Spring Refresher,NaN,NaN,Senior Customer Success Manager,ProcessMaker,True,La Paz,0
2599,City of Toronto,"Javier Aramayo, MBA, CPA, CMA",Manager Compliance and Reporting,"Toronto, Ontario, Canada",https://www.linkedin.com/in/javier-aramayo-mba...,Manager Compliance and Reporting,439.0,444.0,Finance & Business Transformation Leader | Reg...,I’m a dynamic leader with a record of achievem...,...,Native or bilingual proficiency,Manager Compliance and Reporting,"FinTech Program - Blockchain Technology, Model...",NaN,NaN,Manager Compliance and Reporting,City of Toronto,True,"Toronto,Ontario",1
1044,NaN,Edmy MiMi Salazar,Chief Solutions Architect,"Arlington, Virginia, United States",https://www.linkedin.com/in/edmysalazar1/,Financial Solutions Broker | Realtor| Annuitie...,1076.0,1123.0,* Realtor * Financial Solutions Broker,My Mission: Number one to be the best parent a...,...,Native or bilingual proficiency,Financial Solutions Broker | Realtor| Annuitie...,CDPE,The best place to empower our kids financially...,Finacial Educator,Financial Solutions Broker | Realtor| Annuitie...,PASITOS FINANCIEROS,True,"Arlington,Virginia",1
2830,VIVA Bolivia,Guery Alejandro Herbas Rocabado,Desarrollador de Estrategia y Producto,"Santa Cruz, Bolivia",https://www.linkedin.com/in/guery-herbas/,Desarrollador de Estrategia y Producto,1076.0,1081.0,Desarrollador de Estrategia y Producto | CX -U...,NaN,...,NaN,Desarrollador de Estrategia y Producto,Curso de Product Management para Mobile,Facilitador voluntario del Programa Universida...,Facilitador,Desarrollador de Estrategia y Producto,VIVA Bolivia,True,Santa Cruz,0
297,Remax Fortaleza,Fernanda Krutzfeldt Moyano,Gerente comercial,"Santa Cruz, Bolivia",https://www.linkedin.com/in/fernanda-krutzfeld...,Gerente comercial,439.0,437.0,Gerente comercial en Remax Fortaleza,"Me considero una persona seria, responsable, d...",...,NaN,Gerente comercial,NaN,NaN,Voluntaria de construccion,Gerente comercial,Remax Fortaleza,True,Santa Cruz,0
56,Sociedad Boliviana de Cemento S.A. (SOBOCE),Joel Peredo Tapia,Planner,Bolivia,https://www.linkedin.com/in/joel-peredo-tapia-...,Planner,392.0,397.0,Regional Planner en Sociedad Boliviana de Ceme...,NaN,...,NaN,Planner,Certificado Certificación Implementación del P...,NaN,Ayudante de Ciencas Exactas,Planner,Sociedad Boliviana de Cemento S.A. (SOBOCE),True,,0
2245,ITP Instituto Técnico del Petróleo,Diego Peredo Diaz,Instructor,"Villavicencio, Meta, Colombia",https://www.linkedin.com/in/diego-peredo-diaz-...,Instructor,480.0,516.0,Drilling & WO Engineer - \nIADC WellSharp Inst...,"Drilling, workover and completion engineer wit...",...,NaN,Instructor,Well Control Instructor,NaN,NaN,Instructor,Instituto Técnico del Petróleo ITP Training Sc...,True,"Villavicencio,Meta",1
525,Ferroviaria Andina S.A.,Javier Villegas Aparicio,Gerente de RR. HH.,"La Paz, Bolivia",https://www.linkedin.com/in/javier-villegas-ap...,Gerente de RR. HH.,827.0,841.0,Gerente RRHH,Gerente de Recursos Humanos,...,NaN,Gerente de RR. HH.,NaN,NaN,NaN,Gerente de RR. HH.,Ferroviaria Andina S.A.,True,La Paz,0
2597,NaN,Karina Orozco Quintana,JEFE DEL DEPARTAMENTO DE GESTION DE TALENTO HU...,"La Paz, La Paz, Bolivia",https://www.linkedin.com/in/karina-orozco-quin...,JEFE DEL DEPARTAMENTO DE GESTION DE TALENTO HU...,438.0,447.0,GESTIÓN Y DESARROLLO DE TALENTO HUMANO,NaN,...,NaN,JEFE DEL DEPARTAMENTO DE GESTION DE TALENTO HU...,NaN,NaN,NaN,JEFE DEL DEPARTAMENTO DE GESTION DE TALENTO HU...,EMPRESA BOLIVIANA DE ALIMENTOS - EBA,True,"La Paz,La Paz",0
2161,NaN,Eduardo Velarde Camacho,Director comercial,"Cochabamba, Bolivia",https://www.linkedin.com/in/eduardovelardec/,Supervisor de ventas,515.0,529.0,Experto en Ventas y Marketing,Tengo casi 20 años de experiencia me especiali...,...,NaN,Supervisor de ventas,NaN,NaN,NaN,NaN,NaN,False,Cochabamba,0

In [16]:
df_int_1['Len_Headline'] = df_int_1['Headline'].apply(lambda x: len(x) if isinstance(x, str) else 0)

In [17]:
display(df_int_1.describe().T)

,count,mean,std,min,25%,50%,75%,max
Connections,2830.0,1065.489753,1899.338248,300.0,439.0,639.0,1008.0,29896.0
Num Followers,2830.0,1114.562191,2018.970620,299.0,449.0,655.0,1038.5,30451.0
Grade - Education,89.0,530.166966,1979.530988,1.9,84.5,95.0,98.0,9895.0
International,2830.0,0.239223,0.426684,0.0,0.0,0.0,0.0,1.0
Len_Headline,2830.0,64.237809,44.291089,1.0,33.0,51.0,83.0,220.0

In [18]:
df_int_1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2830 entries, 0 to 2899
Data columns (total 37 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Company Name                    2066 non-null   object
 1   Full Name                       2830 non-null   object
 2   Job Title                       2764 non-null   object
 3   Location                        2828 non-null   object
 4   LinkedIn Profile                2830 non-null   object
 5   Title                           2810 non-null   object
 6   Connections                     2830 non-null   float64
 7   Num Followers                   2830 non-null   float64
 8   Headline                        2830 non-null   object
 9   Summary                         1940 non-null   object
 10  Url - Experience                2313 non-null   object
 11  Company - Experience            2816 non-null   object
 12  Summary - Experience            944 non-null    object
 13  Locality - Experience           2207 non-null   object
 14  Is Current - Experience         2830 non-null   bool
 15  Grade - Education               89 non-null     float64
 16  Degree - Education              2767 non-null   object
 17  School Name - Education         2827 non-null   object
 18  Field Of Study - Education      2290 non-null   object
 19  Country                         2828 non-null   object
 20  Location Name                   2826 non-null   object
 21  Summary - Awards                238 non-null    object
 22  Title - Courses                 476 non-null    object
 23  Title - Projects                158 non-null    object
 24  Summary - Projects              113 non-null    object
 25  Language - Languages            1523 non-null   object
 26  Proficiency - Languages         1215 non-null   object
 27  Title - Experience              2818 non-null   object
 28  Title - Certifications          1209 non-null   object
 29  Summary - Volunteering          297 non-null    object
 30  Role - Volunteering             559 non-null    object
 31  Title - Latest Experience       2542 non-null   object
 32  Company - Latest Experience     2529 non-null   object
 33  Is Current - Latest Experience  2830 non-null   bool
 34  City                            2828 non-null   object
 35  International                   2830 non-null   int64
 36  Len_Headline                    2830 non-null   int64
dtypes: bool(2), float64(3), int64(2), object(30)
memory usage: 801.5+ KB

In [19]:
df_int_1.to_csv('../data/df_int_1.csv', index=False, encoding='utf-8')

In [20]:
df_int_1['Connections'].describe()

count     2830.000000
mean      1065.489753
std       1899.338248
min        300.000000
25%        439.000000
50%        639.000000
75%       1008.000000
max      29896.000000
Name: Connections, dtype: float64


 0   Company Name                    - X eliminar
 1   Full Name                       - ???
 2   Job Title                       - X eliminar
 3   Location                        - X eliminar se creo 'Country' y 'City'
 5   Title                           - Categorizar por gerarquia
 6   Connections                     - Outliers arriba del Q3
 7   Num Followers                   - Outliers arriba del Q3
 8   Headline                        - Longitud(+), Idioma, Calidad 1, 2 y 3 (definir criterios)
 9   Summary                         - Categorizar 0: No tiene y 1: Si tiene
 10  Url - Experience                - X eliminar
 11  Company - Experience            - Categorizar por tamaño de empresa 
 12  Summary - Experience            - Categorizar 0: No tiene y 1: Si tiene
 13  Locality - Experience           - X eliminar, se requiere analisis mas profundo para ver casos Remoto
 14  Is Current - Experience         - Cambiar a FALSE: 0 | TRUE: 1
 15  Grade - Education               - X eliminar
 16  Degree - Education              - Categorizar por Nivel de estudio
 17  School Name - Education         - Categorizar por 0: UPB | 1: Universidad Nacional | 2: Universidad extranjera
 18  Field Of Study - Education      - revisar tec de encoding -> descripción % distribución ext | nacionales
 19  Country                         - check
 20  Location Name                   - X eliminar
 21  Summary - Awards                - Categorizar 0: No tiene 1: Si tine
 22  Title - Courses                 - Categorizar 0: No tiene 1: Si tine
 23  Title - Projects                - Categorizar 0: No tiene 1: Si tine
 24  Summary - Projects              - X eliminar
 25  Language - Languages            - Limpiar, categorizar
 26  Proficiency - Languages         - X eliminar
 27  Title - Experience              - X eliminar 
 28  Title - Certifications          - Categorizar 0: No tiene 1: Si tine
 29  Summary - Volunteering          - X eliminar
 30  Role - Volunteering             - Categorizar 0: No tiene 1: Si tine
 31  Title - Latest Experience       - Categorizar 0: No tiene 1: Si tine
 32  Company - Latest Experience     - X eliminar
 33  Is Current - Latest Experience  - X eliminar
 34  City                            - check
 35  International                   - check
 36  Len_Headline                    - check